export const estadosBrasil = {
  acre: {
    nome: "Acre",
    sigla: "AC",
    ddd: "68",
    capital: "Rio Branco",
    regiao: "Norte",
    populacao: "906.876",
    area: "164.112 km²",
    cidades: [
      "Acrelândia",
      "Assis Brasil",
      "Brasiléia",
      "Bujari",
      "Capixaba",
      "Cruzeiro do Sul",
      "Epitaciolândia",
      "Feijó",
      "Jordão",
      "Mâncio Lima",
      "Manoel Urbano",
      "Marechal Thaumaturgo",
      "Plácido de Castro",
      "Porto Acre",
      "Porto Walter",
      "Rio Branco",
      "Rodrigues Alves",
      "Santa Rosa do Purus",
      "Sena Madureira",
      "Senador Guiomard",
      "Tarauacá",
      "Xapuri"
    ]
  },
  alagoas: {
    nome: "Alagoas",
    sigla: "AL",
    ddd: "82",
    capital: "Maceió",
    regiao: "Nordeste",
    populacao: "3.365.351",
    area: "27.767 km²",
    cidades: [
      "Maceió",
      "Arapiraca",
      "Palmeira dos Índios",
      "Rio Largo",
      "Penedo",
      "União dos Palmares",
      "São Miguel dos Campos",
      "Santana do Ipanema",
      "Atalaia",
      "Campo Alegre",
      "Coruripe",
      "Marechal Deodoro",
      "Murici",
      "Pilar",
      "Porto Calvo",
      "Barra de Santo Antônio",
      "Barra de São Miguel",
      "Boca da Mata",
      "Cajueiro",
      "Campestre",
      "Canapi",
      "Capela",
      "Carneiros",
      "Chã Preta",
      "Coité do Nóia",
      "Colônia Leopoldina",
      "Coqueiro Seco",
      "Coração de Maria",
      "Craíbas",
      "Delmiro Gouveia",
      "Dois Riachos",
      "Estrela de Alagoas",
      "Feira Grande",
      "Flexeiras",
      "Girau do Ponciano",
      "Ibateguara",
      "Igaci",
      "Inhapi",
      "Jacaré dos Homens",
      "Japaratinga",
      "Joaquim Gomes",
      "Jundiá",
      "Junqueiro",
      "Lagoa da Canoa",
      "Limoeiro de Anadia",
      "Mata Grande",
      "Matriz de Camaragibe",
      "Messias",
      "Minador do Negrão",
      "Monteirópolis",
      "Murici",
      "Novo Lino",
      "Olho d'Água das Flores",
      "Olho d'Água do Casado",
      "Olivença",
      "Ouro Branco",
      "Palestina",
      "Pão de Açúcar",
      "Pariconha",
      "Paripueira",
      "Passo de Camaragibe",
      "Paulo Jacinto",
      "Penedo",
      "Piaçabuçu",
      "Pilar",
      "Pindoba",
      "Piranhas",
      "Poço das Trincheiras",
      "Porto Calvo",
      "Porto de Pedras",
      "Porto Real do Colégio",
      "Quebrangulo",
      "Rio Largo",
      "Roteiro",
      "Santa Luzia do Norte",
      "Santana do Ipanema",
      "Santo Antônio",
      "São Brás",
      "São José da Laje",
      "São José da Tapera",
      "São Luís do Quitunde",
      "São Miguel dos Campos",
      "São Miguel dos Milagres",
      "São Sebastião",
      "Satuba",
      "Senador Rui Palmeira",
      "Tanque d'Arca",
      "Taquarana",
      "Teotônio Vilela",
      "Traipu",
      "União dos Palmares",
      "Viçosa"
    ]
  }
};

export const getEstadoBySlug = (slug: string) => {
  const estadoKey = slug.toLowerCase();
  return estadosBrasil[estadoKey as keyof typeof estadosBrasil];
};

export const getEstadoByDDD = (ddd: string) => {
  for (const estado of Object.values(estadosBrasil)) {
    if (estado.ddd === ddd) {
      return estado;
    }
  }
  return null;
};