import { ArrowLeft, ArrowUpRight, MapPin, PhoneCall, Search } from "lucide-react";
import { Link } from "wouter";

const faqs = [
  ["O que significa DDD?", "DDD significa Discagem Direta à Distância. É o código de dois algarismos que identifica uma área de numeração telefónica no Brasil."],
  ["Como usar o DDD numa chamada interurbana?", "Para uma ligação interurbana, informe o código da operadora, o DDD de destino e o número de telefone. Confirme sempre a regra aplicável ao seu plano e à operadora."],
  ["Como descobrir o DDD de uma cidade?", "Pesquise o nome da cidade no DDD Brasil ou abra a página do respetivo estado para ver todos os municípios e códigos de área."],
];

export default function DddGuidePage() {
  return <main className="page-shell min-h-screen bg-[#faf3e5] text-[#143d36]">
    <header className="border-b border-[#d9d1bf] bg-[#faf3e5]/90 backdrop-blur"><div className="container flex min-h-[76px] items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={17} /> DDD Brasil</Link><span className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#718378]">Guia de telefonia</span></div></header>
    <article className="container py-14 lg:py-20"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#f06a4d]">Telefonia / guia essencial</div><h1 className="mt-4 font-display text-6xl leading-[0.9] tracking-[-0.07em] sm:text-7xl">O que é DDD?</h1><p className="mt-6 max-w-md text-base leading-7 text-[#5d756c]">Entenda como funcionam os códigos de área no Brasil e encontre, com poucos passos, o DDD de qualquer município.</p><Link href="/#buscar" className="mt-8 inline-flex items-center gap-2 rounded-full bg-[#143d36] px-5 py-3 text-sm font-bold text-[#faf3e5]">Pesquisar um DDD <ArrowUpRight size={16} /></Link></div><div className="relative overflow-hidden rounded-[1.75rem] bg-[#143d36] p-7 text-[#faf3e5] sm:p-10"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(#f5c5a1_1px,transparent_1px)] [background-size:18px_18px]" /><div className="relative"><div className="grid size-12 place-items-center rounded-full bg-[#f06a4d]"><PhoneCall size={22} /></div><p className="mt-10 font-display text-4xl leading-tight">O DDD organiza as ligações por áreas de numeração, não por uma única cidade.</p><p className="mt-5 max-w-xl text-sm leading-6 text-[#c8dbd2]">Um código pode abranger diversos municípios, e uma página de DDD deve ser consultada como um índice territorial: do estado ao município e da cidade ao código de área.</p></div></div></div>
      <section className="mt-16 grid gap-10 border-y border-[#ded4c3] py-14 lg:grid-cols-[0.85fr_1.15fr]"><div><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f06a4d]">Como consultar</div><h2 className="mt-3 font-display text-4xl tracking-[-0.05em]">Três formas de chegar ao código certo</h2></div><ol className="grid gap-3 sm:grid-cols-3">{[["01", "Pesquise", "Escreva a cidade, a UF ou os dois algarismos do DDD."],["02", "Confirme", "Abra a página da cidade ou do DDD e confirme os municípios abrangidos."],["03", "Navegue", "Use as ligações para o estado e encontre códigos relacionados."]].map(([number, title, text]) => <li key={number} className="rounded-2xl border border-[#ded4c3] bg-[#fffaf1] p-5"><span className="font-display text-3xl text-[#f06a4d]">{number}</span><h3 className="mt-7 text-sm font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#5d756c]">{text}</p></li>)}</ol></section>
      <section className="grid gap-8 py-16 lg:grid-cols-[0.75fr_1.25fr]"><div><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f06a4d]">Perguntas frequentes</div><h2 className="mt-3 font-display text-4xl tracking-[-0.05em]">DDD na prática</h2></div><div className="grid gap-3">{faqs.map(([question, answer]) => <details key={question} className="rounded-xl border border-[#ded4c3] bg-[#fffaf1] px-5 py-4"><summary className="cursor-pointer text-sm font-bold">{question}</summary><p className="mt-3 text-sm leading-6 text-[#5d756c]">{answer}</p></details>)}</div></section>
      <section className="rounded-[1.75rem] bg-[#e9deca] p-7 sm:p-10"><div className="grid gap-7 lg:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-[#6c8177]"><MapPin size={14} className="text-[#f06a4d]" /> Próxima consulta</div><h2 className="mt-3 font-display text-4xl tracking-[-0.05em]">Explore os DDDs por território</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[#5d756c]">Comece pelo mapa nacional, abra o estado ou pesquise diretamente o município que procura.</p></div><Link href="/#explorar" className="inline-flex items-center gap-2 self-center rounded-full bg-[#143d36] px-5 py-3 text-sm font-bold text-[#faf3e5]">Abrir atlas <Search size={16} /></Link></div><div className="mt-8 grid gap-3 border-t border-[#cfc3b0] pt-6 sm:grid-cols-3"><Link href="/estado/sp" className="rounded-xl bg-[#faf3e5] p-4 text-sm font-bold hover:text-[#f06a4d]">Pilar: DDD de São Paulo <ArrowUpRight className="mt-4" size={16} /></Link><Link href="/ddd/11" className="rounded-xl bg-[#faf3e5] p-4 text-sm font-bold hover:text-[#f06a4d]">Exemplo: cobertura do DDD 11 <ArrowUpRight className="mt-4" size={16} /></Link><Link href="/cidade/sp/sao-paulo" className="rounded-xl bg-[#faf3e5] p-4 text-sm font-bold hover:text-[#f06a4d]">Ficha: DDD de São Paulo <ArrowUpRight className="mt-4" size={16} /></Link></div></section>
    </article>
  </main>;
}
