import { ArrowUpRight, FileText, Mail, Newspaper, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { PublicNavbar } from "@/components/PublicNavbar";

const pageContent = {
  "/sobre": { eyebrow: "A plataforma", title: "Sobre o Meu DDD", intro: "O Meu DDD organiza a consulta de códigos de área brasileiros em páginas diretas por DDD, estado e município.", sections: [["Consulta territorial", "A plataforma reúne referências para encontrar a área de numeração associada a uma localidade e navegar entre cidades, estados e códigos."], ["Conteúdo explicativo", "Os guias de telefonia ajudam a compreender chamadas, numeração e dúvidas recorrentes de forma simples e objetiva."]] },
  "/contato": { eyebrow: "Contato", title: "Fale sobre o Meu DDD", intro: "Para ajudar a manter as informações claras e úteis, use os canais adequados para cada tipo de necessidade.", sections: [["Correções locais", "Ao encontrar uma informação desatualizada numa página de cidade, use o botão Sugerir alteração local. A indicação pode ser analisada antes de qualquer atualização."], ["Assuntos institucionais e imprensa", "A área de imprensa apresenta o enquadramento da plataforma. Para pedidos institucionais, identifique o assunto e a página de referência ao entrar em contacto."]] },
  "/politica-de-privacidade": { eyebrow: "Privacidade", title: "Política de privacidade", intro: "Esta página apresenta, de forma resumida, como o Meu DDD trata a navegação e os dados necessários para manter o serviço disponível.", sections: [["Dados de navegação", "A plataforma pode registar dados técnicos e estatísticos de uso para compreender pesquisas sem resultado, melhorar a experiência e manter a segurança do serviço."], ["Finalidade", "Informações enviadas em sugestões são utilizadas para analisar a atualização de conteúdos locais. Não utilize esse canal para enviar dados pessoais sensíveis."]] },
  "/termos-de-uso": { eyebrow: "Uso responsável", title: "Termos de uso", intro: "O Meu DDD disponibiliza informações de consulta e conteúdo editorial para finalidade informativa.", sections: [["Uso do conteúdo", "Os dados devem ser confirmados junto de fontes oficiais sempre que a decisão depender de informação atualizada ou de um serviço público específico."], ["Disponibilidade", "A plataforma procura manter as páginas acessíveis e corretas, mas códigos, localidades e serviços podem ser atualizados por entidades competentes."]] },
  "/lgpd": { eyebrow: "Proteção de dados", title: "LGPD e transparência", intro: "A proteção de dados pessoais orienta a forma como o Meu DDD reduz a recolha de informação e comunica as finalidades do tratamento.", sections: [["Minimização", "A plataforma procura tratar apenas as informações necessárias para a navegação, funcionamento técnico e análise de sugestões de conteúdo."], ["Direitos do titular", "Pedidos relacionados a dados pessoais devem identificar claramente o contexto da interação, para que possam ser encaminhados e analisados de forma adequada."]] },
  "/imprensa": { eyebrow: "Imprensa", title: "Informações para imprensa", intro: "O Meu DDD é uma plataforma de consulta de códigos de área brasileiros, com páginas por DDD, estado e município.", sections: [["O que a plataforma oferece", "Consulta territorial, páginas programáticas de referência, guias sobre telefonia e ferramentas de simulação claramente identificadas."], ["Referência de marca", "Ao mencionar a plataforma, utilize o nome Meu DDD e o endereço canónico www.meuddd.com.br."]] },
} as const;

export default function InstitutionalPage() {
  const [location] = useLocation();
  const page = pageContent[location as keyof typeof pageContent] ?? pageContent["/sobre"];
  const Icon = location === "/imprensa" ? Newspaper : location === "/contato" ? Mail : location === "/politica-de-privacidade" || location === "/lgpd" ? ShieldCheck : FileText;

  return (
    <main className="min-h-screen bg-[#faf3e5] text-[#143d36]"><PublicNavbar /><section className="container py-14 sm:py-20"><div className="max-w-3xl"><p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#e8533a]"><Icon size={15} aria-hidden="true" />{page.eyebrow}</p><h1 className="mt-5 font-display text-5xl leading-[0.96] tracking-[-0.045em] sm:text-6xl">{page.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5d756c]">{page.intro}</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{page.sections.map(([title, text]) => <article key={title} className="rounded-3xl border border-[#ded5c4] bg-[#fffaf1] p-6 shadow-[0_14px_36px_rgba(20,61,54,0.06)]"><h2 className="font-display text-2xl tracking-[-0.03em]">{title}</h2><p className="mt-3 text-sm leading-7 text-[#5d756c]">{text}</p></article>)}</div><div className="mt-10 flex flex-wrap gap-3"><Link href="/#buscar" className="pressable inline-flex items-center gap-2 rounded-full bg-[#143d36] px-5 py-3 text-sm font-bold text-[#faf3e5]">Consultar DDD <ArrowUpRight size={16} /></Link><Link href="/guias" className="pressable inline-flex items-center gap-2 rounded-full border border-[#d9d1bf] px-5 py-3 text-sm font-bold text-[#143d36]">Explorar guias</Link></div></section></main>
  );
}
