import { ArrowLeft, ArrowUpRight, MapPin, Phone, Users } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { trpc } from "@/lib/trpc";
import { ShareActions } from "@/components/ShareActions";

const formatPopulation = (value: number | null) => value ? new Intl.NumberFormat("pt-BR").format(value) : "Dado não disponível";

export default function MunicipalityPage() {
  const [, params] = useRoute("/cidade/:uf/:slug");
  const [, setLocation] = useLocation();
  const uf = (params?.uf ?? "").toUpperCase();
  const slug = params?.slug ?? "";
  const detail = trpc.ddd.byMunicipality.useQuery({ uf, slug }, { enabled: /^[A-Z]{2}$/.test(uf) && Boolean(slug) });
  if (detail.isLoading) return <main className="page-shell grid min-h-screen place-items-center bg-[#faf3e5] text-[#143d36]"><p className="text-xs font-bold uppercase tracking-[0.2em]">A localizar município</p></main>;
  if (!detail.data) return <main className="page-shell grid min-h-screen place-items-center bg-[#faf3e5] px-6 text-center text-[#143d36]"><div><h1 className="font-display text-5xl">Município não encontrado</h1><Link href="/" className="mt-7 inline-flex rounded-full bg-[#143d36] px-5 py-3 text-sm font-bold text-[#faf3e5]">Voltar ao atlas</Link></div></main>;

  const { municipality, state, ddd, relatedMunicipalities } = detail.data;
  const mapUrl = `https://www.google.com/maps/search/?api=1&query=${municipality.latitude},${municipality.longitude}`;
  return <main className="page-shell min-h-screen bg-[#faf3e5] text-[#143d36]">
    <header className="border-b border-[#d9d1bf] bg-[#faf3e5]/90 backdrop-blur"><div className="container flex min-h-[76px] items-center justify-between gap-3"><Link href={`/estado/${state.uf.toLowerCase()}`} className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft size={17} /> {state.name}</Link><ShareActions compact path={`/cidade/${uf.toLowerCase()}/${slug}`} title={`DDD de ${municipality.name}, ${state.name}`} /></div></header>
    <section className="container py-14 lg:py-20"><div className="grid gap-10 lg:grid-cols-[1fr_0.9fr]"><div><div className="text-[10px] font-bold uppercase tracking-[0.22em] text-[#f06a4d]">{state.region} / {state.name}</div><h1 className="mt-4 font-display text-6xl leading-[0.9] tracking-[-0.07em] sm:text-7xl">DDD de {municipality.name}</h1><p className="mt-6 max-w-xl text-base leading-7 text-[#5d756c]">{municipality.name} é um município de {state.name}. O código de área associado à localidade é o <strong className="text-[#143d36]">DDD {municipality.ddd}</strong>.</p><div className="mt-8 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#e9deca] p-4"><Users size={17} className="text-[#f06a4d]" /><strong className="mt-4 block font-display text-3xl">{formatPopulation(municipality.populationEstimated)}</strong><span className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#718378]">habitantes · IBGE {municipality.populationReferenceYear}</span></div><Link href={`/ddd/${municipality.ddd}`} className="rounded-2xl bg-[#143d36] p-4 text-[#faf3e5]"><Phone size={17} className="text-[#f5c5a1]" /><strong className="mt-4 block font-display text-3xl">{municipality.ddd}</strong><span className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#b8cec4]">ver municípios do DDD</span></Link></div></div><a href={mapUrl} target="_blank" rel="noreferrer" className="group relative min-h-[320px] overflow-hidden rounded-[1.75rem] bg-[#143d36] p-7 text-[#faf3e5] shadow-[0_24px_55px_rgba(20,61,54,0.18)]"><div className="absolute inset-0 opacity-30 [background-image:radial-gradient(#f5c5a1_1px,transparent_1px)] [background-size:18px_18px]" /><div className="relative flex h-full flex-col justify-between"><div className="flex size-12 items-center justify-center rounded-full bg-[#f06a4d]"><MapPin size={22} /></div><div><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f5c5a1]">Mapa da localidade</div><p className="mt-3 font-display text-4xl leading-none">Abrir {municipality.name}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold">Ver no mapa <ArrowUpRight size={15} /></span></div></div></a></div></section>
    <section className="border-y border-[#ded4c3] bg-[#fffaf1]"><div className="container py-14"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f06a4d]">Território ligado</div><h2 className="mt-3 font-display text-4xl tracking-[-0.05em]">Outras cidades com DDD {municipality.ddd}</h2><p className="mt-4 text-sm leading-6 text-[#6b8177]">Explore localidades do mesmo código de área e volte ao pilar de {state.name} para ver todos os DDDs do estado.</p><button type="button" onClick={() => setLocation(`/estado/${state.uf.toLowerCase()}`)} className="mt-5 text-sm font-bold text-[#f06a4d]">Ver todas as cidades de {state.uf} →</button></div><div className="grid gap-x-6 border-t border-[#e1d6c4] sm:grid-cols-2">{relatedMunicipalities.map(city => <Link key={city.ibgeCode} href={`/cidade/${city.uf.toLowerCase()}/${city.slug}`} className="group flex items-center justify-between gap-3 border-b border-[#e1d6c4] py-3 text-sm font-semibold hover:text-[#f06a4d]"><span>{city.name}</span><ArrowUpRight size={14} className="shrink-0" /></Link>)}</div></div></div></section>
    <section className="container py-16"><div className="max-w-3xl"><div className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#f06a4d]">Perguntas frequentes</div><h2 className="mt-3 font-display text-4xl">Sobre o DDD de {municipality.name}</h2><div className="mt-7 grid gap-3">{[[`Qual é o DDD de ${municipality.name}?`, `O DDD de ${municipality.name}, em ${state.name}, é ${municipality.ddd}.`],[`Como fazer uma ligação para ${municipality.name}?`, `Em ligações interurbanas, use o código da operadora seguido do DDD ${municipality.ddd} e do número de telefone.`],[`Onde consultar outras cidades do DDD ${municipality.ddd}?`, `A página do DDD ${municipality.ddd} reúne os municípios abrangidos e ligações para as respetivas fichas locais.`]].map(([question, answer]) => <details key={question} className="rounded-xl border border-[#ded4c3] bg-[#fffaf1] px-5 py-4"><summary className="cursor-pointer text-sm font-bold">{question}</summary><p className="mt-3 text-sm leading-6 text-[#5d756c]">{answer}</p></details>)}</div></div></section>
  </main>;
}
