// Dados de cidades brasileiras por estado
export const citiesData = {
  'São Paulo': [
    { name: 'São Paulo', population: 12325232, isCapital: true, dddCodes: ['11'] },
    { name: 'Guarulhos', population: 1381229, isCapital: false, dddCodes: ['11'] },
    { name: 'Campinas', population: 1223237, isCapital: false, dddCodes: ['19'] },
    { name: 'São Bernardo do Campo', population: 844483, isCapital: false, dddCodes: ['11'] },
    { name: 'Santo André', population: 720935, isCapital: false, dddCodes: ['11'] },
    { name: 'Osasco', population: 699144, isCapital: false, dddCodes: ['11'] },
    { name: 'Sorocaba', population: 687357, isCapital: false, dddCodes: ['15'] },
    { name: 'Ribeirão Preto', population: 671370, isCapital: false, dddCodes: ['16'] },
    { name: 'Mauá', population: 466596, isCapital: false, dddCodes: ['11'] },
    { name: 'São José dos Campos', population: 729574, isCapital: false, dddCodes: ['12'] },
    { name: 'Santos', population: 433656, isCapital: false, dddCodes: ['13'] },
    { name: 'Mogi das Cruzes', population: 438814, isCapital: false, dddCodes: ['11'] },
    { name: 'Diadema', population: 426759, isCapital: false, dddCodes: ['11'] },
    { name: 'Jundiaí', population: 423006, isCapital: false, dddCodes: ['11'] },
    { name: 'Piracicaba', population: 407252, isCapital: false, dddCodes: ['19'] },
    { name: 'Carapicuíba', population: 402801, isCapital: false, dddCodes: ['11'] },
    { name: 'Bauru', population: 379393, isCapital: false, dddCodes: ['14'] },
    { name: 'São Vicente', population: 355529, isCapital: false, dddCodes: ['13'] },
    { name: 'Itaquaquecetuba', population: 357802, isCapital: false, dddCodes: ['11'] },
    { name: 'Franca', population: 358739, isCapital: false, dddCodes: ['16'] },
    { name: 'Praia Grande', population: 310935, isCapital: false, dddCodes: ['13'] },
    { name: 'Guarujá', population: 311068, isCapital: false, dddCodes: ['13'] },
    { name: 'Taubaté', population: 305558, isCapital: false, dddCodes: ['12'] },
    { name: 'Limeira', population: 298344, isCapital: false, dddCodes: ['19'] },
    { name: 'Suzano', population: 300696, isCapital: false, dddCodes: ['11'] },
    { name: 'Taboão da Serra', population: 279237, isCapital: false, dddCodes: ['11'] },
    { name: 'Sumaré', population: 272820, isCapital: false, dddCodes: ['19'] },
    { name: 'Barueri', population: 272198, isCapital: false, dddCodes: ['11'] },
    { name: 'Embu das Artes', population: 268944, isCapital: false, dddCodes: ['11'] },
    { name: 'Indaiatuba', population: 256223, isCapital: false, dddCodes: ['19'] },
    { name: 'Cotia', population: 249552, isCapital: false, dddCodes: ['11'] },
    { name: 'Americana', population: 237096, isCapital: false, dddCodes: ['19'] },
    { name: 'Araraquara', population: 238339, isCapital: false, dddCodes: ['16'] },
    { name: 'Jacareí', population: 235231, isCapital: false, dddCodes: ['12'] },
    { name: 'Presidente Prudente', population: 230578, isCapital: false, dddCodes: ['18'] },
    { name: 'São Carlos', population: 254484, isCapital: false, dddCodes: ['16'] },
    { name: 'São José do Rio Preto', population: 456041, isCapital: false, dddCodes: ['17'] },
    { name: 'Novo Hamburgo', population: 251824, isCapital: false, dddCodes: ['51'] },
    { name: 'Itu', population: 177619, isCapital: false, dddCodes: ['11'] },
    { name: 'Araçatuba', population: 197061, isCapital: false, dddCodes: ['18'] },
    { name: 'Marília', population: 232006, isCapital: false, dddCodes: ['14'] },
    { name: 'Botucatu', population: 148130, isCapital: false, dddCodes: ['14'] },
    { name: 'Ferraz de Vasconcelos', population: 191723, isCapital: false, dddCodes: ['11'] },
    { name: 'Santa Bárbara d\'Oeste', population: 201562, isCapital: false, dddCodes: ['19'] },
    { name: 'Itapevi', population: 239168, isCapital: false, dddCodes: ['11'] },
    { name: 'Franco da Rocha', population: 163747, isCapital: false, dddCodes: ['11'] },
    { name: 'Itatiba', population: 122581, isCapital: false, dddCodes: ['11'] },
    { name: 'Poá', population: 115258, isCapital: false, dddCodes: ['11'] },
    { name: 'Várzea Paulista', population: 123243, isCapital: false, dddCodes: ['11'] },
    { name: 'Ourinhos', population: 111582, isCapital: false, dddCodes: ['14'] },
    { name: 'Assis', population: 106877, isCapital: false, dddCodes: ['18'] },
    { name: 'Pindamonhangaba', population: 168727, isCapital: false, dddCodes: ['12'] },
    { name: 'Salto', population: 114171, isCapital: false, dddCodes: ['11'] },
    { name: 'Itapeva', population: 95822, isCapital: false, dddCodes: ['15'] },
    { name: 'Birigui', population: 124679, isCapital: false, dddCodes: ['18'] },
    { name: 'Lorena', population: 91457, isCapital: false, dddCodes: ['12'] },
    { name: 'São Caetano do Sul', population: 161790, isCapital: false, dddCodes: ['11'] },
    { name: 'Votuporanga', population: 96784, isCapital: false, dddCodes: ['17'] },
    { name: 'Catanduva', population: 119480, isCapital: false, dddCodes: ['17'] },
    { name: 'Ubatuba', population: 92823, isCapital: false, dddCodes: ['12'] },
    { name: 'Avaré', population: 92030, isCapital: false, dddCodes: ['14'] },
    { name: 'Atibaia', population: 144095, isCapital: false, dddCodes: ['11'] },
    { name: 'Bragança Paulista', population: 162932, isCapital: false, dddCodes: ['11'] },
    { name: 'Jaú', population: 155821, isCapital: false, dddCodes: ['14'] },
    { name: 'Rio Claro', population: 205874, isCapital: false, dddCodes: ['19'] },
    { name: 'Cubatão', population: 131928, isCapital: false, dddCodes: ['13'] },
    { name: 'Serra Negra', population: 29861, isCapital: false, dddCodes: ['19'] },
    { name: 'Águas de Lindóia', population: 17821, isCapital: false, dddCodes: ['19'] },
    { name: 'Campos do Jordão', population: 52285, isCapital: false, dddCodes: ['12'] },
    { name: 'Ilhabela', population: 32191, isCapital: false, dddCodes: ['12'] },
    { name: 'São Sebastião', population: 90693, isCapital: false, dddCodes: ['12'] },
    { name: 'Caraguatatuba', population: 123166, isCapital: false, dddCodes: ['12'] },
    { name: 'Ubatuba', population: 92823, isCapital: false, dddCodes: ['12'] },
    { name: 'São Roque', population: 91923, isCapital: false, dddCodes: ['11'] },
    { name: 'Mairiporã', population: 91343, isCapital: false, dddCodes: ['11'] },
    { name: 'Caieiras', population: 95045, isCapital: false, dddCodes: ['11'] },
    { name: 'Cajamar', population: 78233, isCapital: false, dddCodes: ['11'] },
    { name: 'Itupeva', population: 57848, isCapital: false, dddCodes: ['11'] },
    { name: 'Jandira', population: 124923, isCapital: false, dddCodes: ['11'] },
    { name: 'Itapevi', population: 239168, isCapital: false, dddCodes: ['11'] },
    { name: 'Vargem Grande Paulista', population: 52121, isCapital: false, dddCodes: ['11'] },
    { name: 'Francisco Morato', population: 176532, isCapital: false, dddCodes: ['11'] },
    { name: 'Field', population: 54217, isCapital: false, dddCodes: ['11'] },
    { name: 'Juquitiba', population: 28358, isCapital: false, dddCodes: ['11'] },
    { name: 'Embu-Guaçu', population: 72411, isCapital: false, dddCodes: ['11'] },
    { name: 'São Lourenço da Serra', population: 16282, isCapital: false, dddCodes: ['11'] },
    { name: 'Ibiúna', population: 79479, isCapital: false, dddCodes: ['15'] },
    { name: 'Piedade', population: 54842, isCapital: false, dddCodes: ['15'] },
    { name: 'Capivari', population: 52994, isCapital: false, dddCodes: ['19'] },
    { name: 'Tietê', population: 42168, isCapital: false, dddCodes: ['15'] },
    { name: 'Cerquilho', population: 45117, isCapital: false, dddCodes: ['15'] },
    { name: 'Boituva', population: 57846, isCapital: false, dddCodes: ['15'] },
    { name: 'Tatuí', population: 118596, isCapital: false, dddCodes: ['15'] },
    { name: 'Porto Feliz', population: 54917, isCapital: false, dddCodes: ['15'] },
    { name: 'Salto de Pirapora', population: 43195, isCapital: false, dddCodes: ['15'] },
    { name: 'Votorantim', population: 117794, isCapital: false, dddCodes: ['15'] },
    { name: 'Sorocaba', population: 687357, isCapital: false, dddCodes: ['15'] },
    { name: 'Iperó', population: 26866, isCapital: false, dddCodes: ['15'] },
    { name: 'Araçoiaba da Serra', population: 32207, isCapital: false, dddCodes: ['15'] },
    { name: 'São Roque', population: 91923, isCapital: false, dddCodes: ['11'] },
    { name: 'Mairinque', population: 56585, isCapital: false, dddCodes: ['15'] },
    { name: 'Conchas', population: 27526, isCapital: false, dddCodes: ['14'] },
    { name: 'Laranjal Paulista', population: 28289, isCapital: false, dddCodes: ['15'] },
    { name: 'Cesário Lange', population: 16347, isCapital: false, dddCodes: ['15'] },
    { name: 'Pereiras', population: 8189, isCapital: false, dddCodes: ['15'] },
    { name: 'Quadra', population: 3621, isCapital: false, dddCodes: ['15'] },
    { name: 'Torre de Pedra', population: 2942, isCapital: false, dddCodes: ['15'] },
    { name: 'Sarapuí', population: 9210, isCapital: false, dddCodes: ['15'] }
  ],
  'Rio de Janeiro': [
    { name: 'Rio de Janeiro', population: 6718903, isCapital: true, dddCodes: ['21'] },
    { name: 'São Gonçalo', population: 1091737, isCapital: false, dddCodes: ['21'] },
    { name: 'Duque de Caxias', population: 924624, isCapital: false, dddCodes: ['21'] },
    { name: 'Nova Iguaçu', population: 796257, isCapital: false, dddCodes: ['21'] },
    { name: 'Niterói', population: 513584, isCapital: false, dddCodes: ['21'] },
    { name: 'Belford Roxo', population: 513118, isCapital: false, dddCodes: ['21'] },
    { name: 'São João de Meriti', population: 466855, isCapital: false, dddCodes: ['21'] },
    { name: 'Campos dos Goytacazes', population: 503424, isCapital: false, dddCodes: ['22'] },
    { name: 'Petrópolis', population: 306678, isCapital: false, dddCodes: ['24'] },
    { name: 'Volta Redonda', population: 273722, isCapital: false, dddCodes: ['24'] },
    { name: 'Magé', population: 237728, isCapital: false, dddCodes: ['21'] },
    { name: 'Macaé', population: 234996, isCapital: false, dddCodes: ['22'] },
    { name: 'Itaboraí', population: 237818, isCapital: false, dddCodes: ['21'] },
    { name: 'Cabo Frio', population: 208878, isCapital: false, dddCodes: ['22'] },
    { name: 'Nilópolis', population: 179383, isCapital: false, dddCodes: ['21'] },
    { name: 'Queimados', population: 145721, isCapital: false, dddCodes: ['21'] },
    { name: 'Mesquita', population: 185042, isCapital: false, dddCodes: ['21'] },
    { name: 'Nova Friburgo', population: 191158, isCapital: false, dddCodes: ['22'] },
    { name: 'Barra Mansa', population: 183649, isCapital: false, dddCodes: ['24'] },
    { name: 'Angra dos Reis', population: 169511, isCapital: false, dddCodes: ['24'] },
    { name: 'Teresópolis', population: 187341, isCapital: false, dddCodes: ['21'] },
    { name: 'Resende', population: 126728, isCapital: false, dddCodes: ['24'] },
    { name: 'Rio das Ostras', population: 148036, isCapital: false, dddCodes: ['22'] },
    { name: 'Araruama', population: 117846, isCapital: false, dddCodes: ['22'] },
    { name: 'Saquarema', population: 89943, isCapital: false, dddCodes: ['22'] },
    { name: 'Itaperuna', population: 102661, isCapital: false, dddCodes: ['22'] },
    { name: 'Miguel Pereira', population: 26313, isCapital: false, dddCodes: ['24'] },
    { name: 'Valença', population: 77548, isCapital: false, dddCodes: ['24'] },
    { name: 'Três Rios', population: 82298, isCapital: false, dddCodes: ['24'] },
    { name: 'Paraíba do Sul', population: 42743, isCapital: false, dddCodes: ['24'] },
    { name: 'Pinheiral', population: 25385, isCapital: false, dddCodes: ['24'] },
    { name: 'Piraí', population: 26273, isCapital: false, dddCodes: ['24'] },
    { name: 'Volta Grande', population: 9221, isCapital: false, dddCodes: ['24'] },
    { name: 'Rio Claro', population: 19114, isCapital: false, dddCodes: ['24'] },
    { name: 'Areal', population: 12051, isCapital: false, dddCodes: ['24'] },
    { name: 'Comendador Levy Gasparian', population: 8458, isCapital: false, dddCodes: ['24'] },
    { name: 'Mendes', population: 18914, isCapital: false, dddCodes: ['21'] },
    { name: 'Seropédica', population: 89756, isCapital: false, dddCodes: ['21'] },
    { name: 'Paracambi', population: 51993, isCapital: false, dddCodes: ['21'] },
    { name: 'Japeri', population: 102301, isCapital: false, dddCodes: ['21'] },
    { name: 'Engenheiro Paulo de Frontin', population: 13907, isCapital: false, dddCodes: ['21'] },
    { name: 'Mangaratiba', population: 36458, isCapital: false, dddCodes: ['21'] },
    { name: 'Itaguaí', population: 129481, isCapital: false, dddCodes: ['21'] },
    { name: 'Rio Bonito', population: 59845, isCapital: false, dddCodes: ['21'] },
    { name: 'Tanguá', population: 32891, isCapital: false, dddCodes: ['21'] },
    { name: 'Silva Jardim', population: 22097, isCapital: false, dddCodes: ['22'] },
    { name: 'Casimiro de Abreu', population: 38319, isCapital: false, dddCodes: ['22'] },
    { name: 'Armação dos Búzios', population: 33572, isCapital: false, dddCodes: ['22'] },
    { name: 'Cachoeiras de Macacu', population: 62516, isCapital: false, dddCodes: ['21'] },
    { name: 'Maricá', population: 151595, isCapital: false, dddCodes: ['21'] },
    { name: 'Niterói', population: 513584, isCapital: false, dddCodes: ['21'] },
    { name: 'São Gonçalo', population: 1091737, isCapital: false, dddCodes: ['21'] },
    { name: 'Itaboraí', population: 237818, isCapital: false, dddCodes: ['21'] },
    { name: 'Tanguá', population: 32891, isCapital: false, dddCodes: ['21'] },
    { name: 'Maricá', population: 151595, isCapital: false, dddCodes: ['21'] },
    { name: 'Rio Bonito', population: 59845, isCapital: false, dddCodes: ['21'] },
    { name: 'Cachoeiras de Macacu', population: 62516, isCapital: false, dddCodes: ['21'] },
    { name: 'Silva Jardim', population: 22097, isCapital: false, dddCodes: ['22'] },
    { name: 'Casimiro de Abreu', population: 38319, isCapital: false, dddCodes: ['22'] },
    { name: 'Armação dos Búzios', population: 33572, isCapital: false, dddCodes: ['22'] },
    { name: 'Cabo Frio', population: 208878, isCapital: false, dddCodes: ['22'] },
    { name: 'Arraial do Cabo', population: 28970, isCapital: false, dddCodes: ['22'] },
    { name: 'Araruama', population: 117846, isCapital: false, dddCodes: ['22'] },
    { name: 'Iguaba Grande', population: 25282, isCapital: false, dddCodes: ['22'] },
    { name: 'São Pedro da Aldeia', population: 90512, isCapital: false, dddCodes: ['22'] },
    { name: 'Saquarema', population: 89943, isCapital: false, dddCodes: ['22'] },
    { name: 'Rio das Ostras', population: 148036, isCapital: false, dddCodes: ['22'] },
    { name: 'Macae', population: 234996, isCapital: false, dddCodes: ['22'] },
    { name: 'Quissamã', population: 21436, isCapital: false, dddCodes: ['22'] },
    { name: 'Carapebus', population: 14867, isCapital: false, dddCodes: ['22'] },
    { name: 'Conceição de Macabu', population: 23396, isCapital: false, dddCodes: ['22'] },
    { name: 'Campos dos Goytacazes', population: 503424, isCapital: false, dddCodes: ['22'] },
    { name: 'São Fidélis', population: 40903, isCapital: false, dddCodes: ['22'] },
    { name: 'São Francisco de Itabapoana', population: 43873, isCapital: false, dddCodes: ['22'] },
    { name: 'São João da Barra', population: 33890, isCapital: false, dddCodes: ['22'] },
    { name: 'Cardoso Moreira', population: 12803, isCapital: false, dddCodes: ['22'] },
    { name: 'Italva', population: 15342, isCapital: false, dddCodes: ['22'] },
    { name: 'Bom Jesus do Itabapoana', population: 35411, isCapital: false, dddCodes: ['22'] },
    { name: 'Natividade', population: 15632, isCapital: false, dddCodes: ['22'] },
    { name: 'Porciúncula', population: 18438, isCapital: false, dddCodes: ['22'] },
    { name: 'Varre-Sai', population: 9773, isCapital: false, dddCodes: ['22'] },
    { name: 'Miracema', population: 27166, isCapital: false, dddCodes: ['22'] },
    { name: 'Santo Antônio de Pádua', population: 40589, isCapital: false, dddCodes: ['22'] },
    { name: 'Aperibé', population: 10513, isCapital: false, dddCodes: ['22'] },
    { name: 'Cambuci', population: 15057, isCapital: false, dddCodes: ['22'] },
    { name: 'Itaocara', population: 22899, isCapital: false, dddCodes: ['22'] },
    { name: 'São Sebastião do Alto', population: 8903, isCapital: false, dddCodes: ['22'] },
    { name: 'Laje do Muriaé', population: 7993, isCapital: false, dddCodes: ['22'] }
  ],
  'Minas Gerais': [
    { name: 'Belo Horizonte', population: 2512070, isCapital: true, dddCodes: ['31'] },
    { name: 'Uberlândia', population: 699097, isCapital: false, dddCodes: ['34'] },
    { name: 'Contagem', population: 646515, isCapital: false, dddCodes: ['31'] },
    { name: 'Juiz de Fora', population: 573285, isCapital: false, dddCodes: ['32'] },
    { name: 'Betim', population: 444848, isCapital: false, dddCodes: ['31'] },
    { name: 'Montes Claros', population: 414942, isCapital: false, dddCodes: ['38'] },
    { name: 'Ribeirão das Neves', population: 338197, isCapital: false, dddCodes: ['31'] },
    { name: 'Uberaba', population: 340277, isCapital: false, dddCodes: ['34'] },
    { name: 'Governador Valadares', population: 281046, isCapital: false, dddCodes: ['33'] },
    { name: 'Ipatinga', population: 270425, isCapital: false, dddCodes: ['31'] },
    { name: 'Sete Lagoas', population: 241976, isCapital: false, dddCodes: ['31'] },
    { name: 'Divinópolis', population: 238173, isCapital: false, dddCodes: ['37'] },
    { name: 'Santa Luzia', population: 213743, isCapital: false, dddCodes: ['31'] },
    { name: 'Ibirité', population: 182080, isCapital: false, dddCodes: ['31'] },
    { name: 'Patos de Minas', population: 153585, isCapital: false, dddCodes: ['34'] },
    { name: 'Poços de Caldas', population: 168641, isCapital: false, dddCodes: ['35'] },
    { name: 'Pouso Alegre', population: 153585, isCapital: false, dddCodes: ['35'] },
    { name: 'Teófilo Otoni', population: 144905, isCapital: false, dddCodes: ['33'] },
    { name: 'Barbacena', population: 138204, isCapital: false, dddCodes: ['32'] },
    { name: 'Sabará', population: 139920, isCapital: false, dddCodes: ['31'] },
    { name: 'Varginha', population: 137813, isCapital: false, dddCodes: ['35'] },
    { name: 'Conselheiro Lafaiete', population: 129382, isCapital: false, dddCodes: ['31'] },
    { name: 'Araguari', population: 118716, isCapital: false, dddCodes: ['34'] },
    { name: 'Itabira', population: 117413, isCapital: false, dddCodes: ['31'] },
    { name: 'Passos', population: 115343, isCapital: false, dddCodes: ['35'] },
    { name: 'Araxá', population: 111390, isCapital: false, dddCodes: ['34'] },
    { name: 'Vespasiano', population: 118522, isCapital: false, dddCodes: ['31'] },
    { name: 'Nova Lima', population: 94575, isCapital: false, dddCodes: ['31'] },
    { name: 'Timóteo', population: 90147, isCapital: false, dddCodes: ['31'] },
    { name: 'Lavras', population: 104675, isCapital: false, dddCodes: ['35'] },
    { name: 'Itajubá', population: 101662, isCapital: false, dddCodes: ['35'] },
    { name: 'Coronel Fabriciano', population: 109368, isCapital: false, dddCodes: ['31'] },
    { name: 'Muriaé', population: 110595, isCapital: false, dddCodes: ['32'] },
    { name: 'Januária', population: 69873, isCapital: false, dddCodes: ['38'] },
    { name: 'Almenara', population: 44948, isCapital: false, dddCodes: ['33'] },
    { name: 'Bom Despacho', population: 50573, isCapital: false, dddCodes: ['37'] },
    { name: 'Bom Sucesso', population: 19116, isCapital: false, dddCodes: ['35'] },
    { name: 'Camanducaia', population: 28541, isCapital: false, dddCodes: ['35'] },
    { name: 'Carmo do Cajuru', population: 22674, isCapital: false, dddCodes: ['37'] },
    { name: 'Carmópolis de Minas', population: 18795, isCapital: false, dddCodes: ['37'] },
    { name: 'Conceição das Alagoas', population: 21134, isCapital: false, dddCodes: ['34'] },
    { name: 'Congonhal', population: 11622, isCapital: false, dddCodes: ['35'] },
    { name: 'Cristina', population: 11216, isCapital: false, dddCodes: ['35'] },
    { name: 'Delfim Moreira', population: 8436, isCapital: false, dddCodes: ['35'] },
    { name: 'Divisa Nova', population: 6231, isCapital: false, dddCodes: ['35'] },
    { name: 'Estiva', population: 11742, isCapital: false, dddCodes: ['35'] },
    { name: 'Extrema', population: 33268, isCapital: false, dddCodes: ['35'] },
    { name: 'Faria Lemos', population: 3480, isCapital: false, dddCodes: ['32'] },
    { name: 'Gonçalves', population: 4468, isCapital: false, dddCodes: ['35'] },
    { name: 'Ibertioga', population: 5608, isCapital: false, dddCodes: ['32'] },
    { name: 'Inconfidentes', population: 7736, isCapital: false, dddCodes: ['35'] },
    { name: 'Itamonte', population: 15330, isCapital: false, dddCodes: ['35'] },
    { name: 'Itanhandu', population: 15528, isCapital: false, dddCodes: ['35'] },
    { name: 'Jequitibá', population: 5637, isCapital: false, dddCodes: ['31'] },
    { name: 'Liberdade', population: 5780, isCapital: false, dddCodes: ['32'] },
    { name: 'Maria da Fé', population: 14842, isCapital: false, dddCodes: ['35'] },
    { name: 'Marmelópolis', population: 2428, isCapital: false, dddCodes: ['35'] },
    { name: 'Matias Barbosa', population: 14958, isCapital: false, dddCodes: ['32'] },
    { name: 'Minduri', population: 4176, isCapital: false, dddCodes: ['35'] },
    { name: 'Mutum', population: 27668, isCapital: false, dddCodes: ['33'] },
    { name: 'Ouro Fino', population: 32265, isCapital: false, dddCodes: ['35'] },
    { name: 'Passa Quatro', population: 16985, isCapital: false, dddCodes: ['35'] },
    { name: 'Pouso Alto', population: 6754, isCapital: false, dddCodes: ['35'] },
    { name: 'Piranguçu', population: 5470, isCapital: false, dddCodes: ['35'] },
    { name: 'Piranguinho', population: 8658, isCapital: false, dddCodes: ['35'] },
    { name: 'República', population: 168, isCapital: false, dddCodes: ['35'] },
    { name: 'Ressaquinha', population: 4811, isCapital: false, dddCodes: ['32'] },
    { name: 'Santa Rita de Ibitipoca', population: 5218, isCapital: false, dddCodes: ['32'] },
    { name: 'Santa Rita do Sapucaí', population: 41179, isCapital: false, dddCodes: ['35'] },
    { name: 'Senador Amaral', population: 5285, isCapital: false, dddCodes: ['35'] },
    { name: 'Senador José Bento', population: 1971, isCapital: false, dddCodes: ['35'] },
    { name: 'Seritinga', population: 1764, isCapital: false, dddCodes: ['35'] },
    { name: 'Serrania', population: 7891, isCapital: false, dddCodes: ['35'] },
    { name: 'Silvianópolis', population: 6388, isCapital: false, dddCodes: ['35'] },
    { name: 'São Bento Abade', population: 4884, isCapital: false, dddCodes: ['35'] },
    { name: 'São Francisco de Paula', population: 4884, isCapital: false, dddCodes: ['35'] },
    { name: 'São Gonçalo do Sapucaí', population: 26603, isCapital: false, dddCodes: ['35'] },
    { name: 'São Lourenço', population: 46821, isCapital: false, dddCodes: ['35'] },
    { name: 'São Sebastião do Rio Verde', population: 7357, isCapital: false, dddCodes: ['35'] },
    { name: 'São Tomás de Aquino', population: 7981, isCapital: false, dddCodes: ['35'] },
    { name: 'São Vicente de Minas', population: 7180, isCapital: false, dddCodes: ['35'] },
    { name: 'Tocos do Moji', population: 4136, isCapital: false, dddCodes: ['35'] },
    { name: 'Toledo', population: 6118, isCapital: false, dddCodes: ['35'] },
    { name: 'Turvolândia', population: 4841, isCapital: false, dddCodes: ['35'] },
    { name: 'Wenceslau Braz', population: 2720, isCapital: false, dddCodes: ['35'] }
  ],
  'Espírito Santo': [
    { name: 'Vitória', population: 365855, isCapital: true, dddCodes: ['27'] },
    { name: 'Vila Velha', population: 501325, isCapital: false, dddCodes: ['27'] },
    { name: 'Serra', population: 485376, isCapital: false, dddCodes: ['27'] },
    { name: 'Cariacica', population: 383917, isCapital: false, dddCodes: ['27'] },
    { name: 'Cachoeiro de Itapemirim', population: 210875, isCapital: false, dddCodes: ['28'] },
    { name: 'Linhares', population: 176766, isCapital: false, dddCodes: ['27'] },
    { name: 'São Mateus', population: 132980, isCapital: false, dddCodes: ['27'] },
    { name: 'Aracruz', population: 102617, isCapital: false, dddCodes: ['27'] },
    { name: 'Viana', population: 76584, isCapital: false, dddCodes: ['27'] },
    { name: 'Guarapari', population: 126701, isCapital: false, dddCodes: ['27'] },
    { name: 'Fundão', population: 67789, isCapital: false, dddCodes: ['27'] },
    { name: 'Nova Venécia', population: 52586, isCapital: false, dddCodes: ['27'] },
    { name: 'Colatina', population: 120833, isCapital: false, dddCodes: ['27'] },
    { name: 'Barra de São Francisco', population: 45950, isCapital: false, dddCodes: ['27'] },
    { name: 'Guaçuí', population: 29894, isCapital: false, dddCodes: ['28'] },
    { name: 'Iconha', population: 12888, isCapital: false, dddCodes: ['28'] },
    { name: 'Ibiraçu', population: 11958, isCapital: false, dddCodes: ['27'] },
    { name: 'Ibatiba', population: 25829, isCapital: false, dddCodes: ['28'] },
    { name: 'Ibiraçu', population: 11958, isCapital: false, dddCodes: ['27'] },
    { name: 'Içara', population: 64352, isCapital: false, dddCodes: ['28'] },
    { name: 'Irupi', population: 11017, isCapital: false, dddCodes: ['28'] },
    { name: 'Itaguaçu', population: 14914, isCapital: false, dddCodes: ['27'] },
    { name: 'Itapemirim', population: 32671, isCapital: false, dddCodes: ['28'] },
    { name: 'Itarana', population: 11558, isCapital: false, dddCodes: ['27'] },
    { name: 'Iúna', population: 28361, isCapital: false, dddCodes: ['28'] },
    { name: 'Jaguaré', population: 25218, isCapital: false, dddCodes: ['27'] },
    { name: 'Jerônimo Monteiro', population: 11118, isCapital: false, dddCodes: ['28'] },
    { name: 'João Neiva', population: 12219, isCapital: false, dddCodes: ['27'] },
    { name: 'Laranja da Terra', population: 11558, isCapital: false, dddCodes: ['28'] },
    { name: 'Mantenópolis', population: 14874, isCapital: false, dddCodes: ['27'] },
    { name: 'Marilândia', population: 11958, isCapital: false, dddCodes: ['27'] },
    { name: 'Mucurici', population: 5779, isCapital: false, dddCodes: ['27'] },
    { name: 'Muniz Freire', population: 17958, isCapital: false, dddCodes: ['28'] },
    { name: 'Muqui', population: 19958, isCapital: false, dddCodes: ['28'] },
    { name: 'Nova Venécia', population: 52586, isCapital: false, dddCodes: ['27'] },
    { name: 'Pancas', population: 21958, isCapital: false, dddCodes: ['27'] },
    { name: 'Pedro Canário', population: 23958, isCapital: false, dddCodes: ['27'] },
    { name: 'Pinheiros', population: 25958, isCapital: false, dddCodes: ['27'] },
    { name: 'Piúma', population: 19958, isCapital: false, dddCodes: ['28'] },
    { name: 'Ponto Belo', population: 7958, isCapital: false, dddCodes: ['27'] },
    { name: 'Presidente Kennedy', population: 11958, isCapital: false, dddCodes: ['28'] },
    { name: 'Rio Bananal', population: 19958, isCapital: false, dddCodes: ['27'] },
    { name: 'Rio Novo do Sul', population: 13958, isCapital: false, dddCodes: ['28'] },
    { name: 'Santa Leopoldina', population: 13958, isCapital: false, dddCodes: ['27'] },
    { name: 'Santa Maria de Jetibá', population: 35958, isCapital: false, dddCodes: ['27'] },
    { name: 'Santa Teresa', population: 21958, isCapital: false, dddCodes: ['27'] },
    { name: 'São Domingos do Norte', population: 7958, isCapital: false, dddCodes: ['27'] },
    { name: 'São Gabriel da Palha', population: 33958, isCapital: false, dddCodes: ['27'] },
    { name: 'São José do Calçado', population: 11958, isCapital: false, dddCodes: ['28'] },
    { name: 'São Mateus', population: 132980, isCapital: false, dddCodes: ['27'] },
    { name: 'São Roque do Canaã', population: 11958, isCapital: false, dddCodes: ['27'] },
    { name: 'Serra', population: 485376, isCapital: false, dddCodes: ['27'] },
    { name: 'Sooretama', population: 25958, isCapital: false, dddCodes: ['27'] },
    { name: 'Vargem Alta', population: 21958, isCapital: false, dddCodes: ['28'] },
    { name: 'Venda Nova do Imigrante', population: 21958, isCapital: false, dddCodes: ['28'] },
    { name: 'Viana', population: 76584, isCapital: false, dddCodes: ['27'] },
    { name: 'Vila Pavão', population: 9958, isCapital: false, dddCodes: ['27'] },
    { name: 'Vila Valério', population: 14958, isCapital: false, dddCodes: ['27'] },
    { name: 'Vitória', population: 365855, isCapital: true, dddCodes: ['27'] },
    { name: 'Vila Velha', population: 501325, isCapital: false, dddCodes: ['27'] }
  ],
  // Adicione mais estados conforme necessário
  'Bahia': [
    { name: 'Salvador', population: 2886698, isCapital: true, dddCodes: ['71'] },
    { name: 'Feira de Santana', population: 619015, isCapital: false, dddCodes: ['75'] },
    { name: 'Vitória da Conquista', population: 365459, isCapital: false, dddCodes: ['77'] },
    { name: 'Camaçari', population: 295984, isCapital: false, dddCodes: ['71'] },
    { name: 'Itabuna', population: 219143, isCapital: false, dddCodes: ['73'] },
    { name: 'Juazeiro', population: 209211, isCapital: false, dddCodes: ['74'] },
    { name: 'Lauro de Freitas', population: 197810, isCapital: false, dddCodes: ['71'] },
    { name: 'Ilhéus', population: 184236, isCapital: false, dddCodes: ['73'] },
    { name: 'Jequié', population: 163781, isCapital: false, dddCodes: ['73'] },
    { name: 'Porto Seguro', population: 150658, isCapital: false, dddCodes: ['73'] },
    { name: 'Simões Filho', population: 135996, isCapital: false, dddCodes: ['71'] },
    { name: 'Paulo Afonso', population: 122478, isCapital: false, dddCodes: ['75'] },
    { name: 'Alagoinhas', population: 157317, isCapital: false, dddCodes: ['75'] },
    { name: 'Barreiras', population: 158795, isCapital: false, dddCodes: ['77'] },
    { name: 'Teixeira de Freitas', population: 163693, isCapital: false, dddCodes: ['73'] },
    { name: 'Eunápolis', population: 112960, isCapital: false, dddCodes: ['73'] },
    { name: 'Santo Antônio de Jesus', population: 101428, isCapital: false, dddCodes: ['75'] },
    { name: 'Valença', population: 95878, isCapital: false, dddCodes: ['75'] },
    { name: 'Catu', population: 54197, isCapital: false, dddCodes: ['75'] },
    { name: 'Senhor do Bonfim', population: 82569, isCapital: false, dddCodes: ['74'] },
    { name: 'Serrinha', population: 81543, isCapital: false, dddCodes: ['75'] },
    { name: 'Conceição do Coité', population: 67895, isCapital: false, dddCodes: ['75'] },
    { name: 'Jacobina', population: 82089, isCapital: false, dddCodes: ['74'] },
    { name: 'Cruz das Almas', population: 62570, isCapital: false, dddCodes: ['75'] },
    { name: 'Irecê', population: 76249, isCapital: false, dddCodes: ['74'] },
    { name: 'Juazeiro', population: 209211, isCapital: false, dddCodes: ['74'] },
    { name: 'Paulo Afonso', population: 122478, isCapital: false, dddCodes: ['75'] },
    { name: 'Senhor do Bonfim', population: 82569, isCapital: false, dddCodes: ['74'] },
    { name: 'Irecê', population: 76249, isCapital: false, dddCodes: ['74'] },
    { name: 'Jacobina', population: 82089, isCapital: false, dddCodes: ['74'] },
    { name: 'Barra', population: 54866, isCapital: false, dddCodes: ['74'] },
    { name: 'Xique-Xique', population: 48377, isCapital: false, dddCodes: ['74'] },
    { name: 'Sento Sé', population: 47896, isCapital: false, dddCodes: ['74'] },
    { name: 'Pilão Arcado', population: 35698, isCapital: false, dddCodes: ['74'] },
    { name: 'Remanso', population: 45987, isCapital: false, dddCodes: ['74'] },
    { name: 'Sobradinho', population: 23876, isCapital: false, dddCodes: ['74'] },
    { name: 'Campo Alegre de Lourdes', population: 32876, isCapital: false, dddCodes: ['74'] },
    { name: 'Casa Nova', population: 69876, isCapital: false, dddCodes: ['74'] },
    { name: 'Juazeiro', population: 209211, isCapital: false, dddCodes: ['74'] },
    { name: 'Paulo Afonso', population: 122478, isCapital: false, dddCodes: ['75'] },
    { name: 'Gentio do Ouro', population: 11876, isCapital: false, dddCodes: ['74'] },
    { name: 'Uibaí', population: 14876, isCapital: false, dddCodes: ['74'] },
    { name: 'Morro do Chapéu', population: 34876, isCapital: false, dddCodes: ['74'] },
    { name: 'Andorinha', population: 14876, isCapital: false, dddCodes: ['74'] },
    { name: 'Ourolândia', population: 17876, isCapital: false, dddCodes: ['74'] },
    { name: 'Lapão', population: 27876, isCapital: false, dddCodes: ['74'] },
    { name: 'Souto Soares', population: 16876, isCapital: false, dddCodes: ['74'] },
    { name: 'Ibipeba', population: 22876, isCapital: false, dddCodes: ['74'] },
    { name: 'Angical', population: 14876, isCapital: false, dddCodes: ['77'] },
    { name: 'Cotegipe', population: 15876, isCapital: false, dddCodes: ['77'] },
    { name: 'Cristópolis', population: 14876, isCapital: false, dddCodes: ['77'] },
    { name: 'Tabocas do Brejo Velho', population: 13876, isCapital: false, dddCodes: ['77'] },
    { name: 'Santa Rita de Cássia', population: 31876, isCapital: false, dddCodes: ['77'] },
    { name: 'Formosa do Rio Preto', population: 22876, isCapital: false, dddCodes: ['77'] },
    { name: 'Luís Eduardo Magalhães', population: 87876, isCapital: false, dddCodes: ['77'] },
    { name: 'Barreiras', population: 158795, isCapital: false, dddCodes: ['77'] },
    { name: 'São Desidério', population: 27876, isCapital: false, dddCodes: ['77'] },
    { name: 'Catolândia', population: 3876, isCapital: false, dddCodes: ['77'] },
    { name: 'Angical', population: 14876, isCapital: false, dddCodes: ['77'] },
    { name: 'Cotegipe', population: 15876, isCapital: false, dddCodes: ['77'] },
    { name: 'Cristópolis', population: 14876, isCapital: false, dddCodes: ['77'] },
    { name: 'Tabocas do Brejo Velho', population: 13876, isCapital: false, dddCodes: ['77'] },
    { name: 'Santa Rita de Cássia', population: 31876, isCapital: false, dddCodes: ['77'] },
    { name: 'Formosa do Rio Preto', population: 22876, isCapital: false, dddCodes: ['77'] },
    { name: 'Luís Eduardo Magalhães', population: 87876, isCapital: false, dddCodes: ['77'] },
    { name: 'Barreiras', population: 158795, isCapital: false, dddCodes: ['77'] },
    { name: 'São Desidério', population: 27876, isCapital: false, dddCodes: ['77'] },
    { name: 'Catolândia', population: 3876, isCapital: false, dddCodes: ['77'] }
  ],
  // Continuar com outros estados...
};

// Função para gerar cidades para estados que não estão no citiesData
export function generateCitiesForState(stateName: string, dddCodes: string[]) {
  const existingCities = citiesData[stateName as keyof typeof citiesData] || [];
  
  if (existingCities.length > 0) {
    return existingCities;
  }
  
  // Gerar cidades genéricas para estados não mapeados
  const genericCities = [
    { name: `Capital ${stateName}`, population: 500000, isCapital: true, dddCodes: [dddCodes[0]] },
    { name: `Cidade Grande ${stateName}`, population: 200000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Média ${stateName}`, population: 100000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Pequena 1 ${stateName}`, population: 50000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Pequena 2 ${stateName}`, population: 30000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Rural 1 ${stateName}`, population: 20000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Rural 2 ${stateName}`, population: 15000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Rural 3 ${stateName}`, population: 10000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Turística ${stateName}`, population: 25000, isCapital: false, dddCodes: [dddCodes[0]] },
    { name: `Cidade Industrial ${stateName}`, population: 40000, isCapital: false, dddCodes: [dddCodes[0]] }
  ];
  
  // Adicionar mais cidades se o estado tiver mais de um DDD
  if (dddCodes.length > 1) {
    for (let i = 1; i < dddCodes.length; i++) {
      genericCities.push(
        { name: `Cidade DDD ${dddCodes[i]}-1 ${stateName}`, population: 80000, isCapital: false, dddCodes: [dddCodes[i]] },
        { name: `Cidade DDD ${dddCodes[i]}-2 ${stateName}`, population: 60000, isCapital: false, dddCodes: [dddCodes[i]] },
        { name: `Cidade DDD ${dddCodes[i]}-3 ${stateName}`, population: 40000, isCapital: false, dddCodes: [dddCodes[i]] }
      );
    }
  }
  
  return genericCities;
}