# -*- coding: utf-8 -*-
"""
Biblioteca de vozes regionais para a geração editorial das fichas de municípios.

Cada perfil define como um redator LOCAL escreveria sobre a sua própria terra:
marcas de oralidade, expressões e gírias do estado, costumes e jeitos de vida,
formas de tratar o leitor e fechos típicos. O motor editorial (engine.py) usa
esses perfis com sorteio determinístico por município, de modo que a leitura
soe regional e nenhuma ficha repita a mesma estrutura da vizinha.
"""

PERFIS = {
    "AC": {
        "gírias": ["é nóis", "bom demais", "da hora", "pelas bandas daqui", "dar uma passada", "bater um papo"],
        "costumes": ["cultura ribeirinha e vida à beira do rio", "festival de peixe moqueado", "tapioca e açaí no café da tarde", "forró pé-de-serra nas festas de interior", "festivais gastronômicos da floresta", "tradição dos povos indígenas e seringueiros"],
        "tratamento": "amigo",
        "marcas_orais": ["pra falar a verdade", "é bonito demais", "se tu for por lá", "é isso que eu te digo", "pode crer", "dá uma olhada só"],
        "fechos": ["Vem pro Acre, que a floresta tá te esperando.", "Aqui ninguém tem pressa e todo mundo se conhece — aparece.", "O Acre é discreto no mapa e enorme no coração."],
        "regiao": "Norte",
    },
    "AL": {
        "gírias": ["oxente", "muita coisa boa", "arretado", "pelas banda de", "arrastapé", "bom demais"],
        "costumes": ["carnaval de rua em Maceió", "maracatu e coco de roda", "queijo coalho com mel de rapadura", "praças à beira-mar ao entardecer", "festas juninas nas praças", "bancos de areia do Rio São Francisco"],
        "tratamento": "meu rei",
        "marcas_orais": ["é coisa de doido a beleza daqui", "oxente, que bom", "pode apostar", "é bom demais, viu", "tu não vai se arrepender"],
        "fechos": ["Vem ver com os teus olhos — Alagoas é de doer.", "Tô te esperando no litoral, vem!", "Alagoas é pequena no mapa e gigante no coração."],
        "regiao": "Nordeste",
    },
    "AP": {
        "gírias": ["bixo", "da massa", "muito da hora", "se liga", "rolê", "tá de parabéns"],
        "costumes": ["festival do açaí de Macapá", "marabaixo e cultura afroramazônica", "feiras de peixe à madrugada", "pescarias nos rios amazônicos", "tucupi e jambu na cozinha", "cultura de fronteira com o Caribe"],
        "tratamento": "bixo",
        "marcas_orais": ["se liga nessa", "bixo, é demais", "tu não imagina", "é de chorar de tão bonito", "pode apostar"],
        "fechos": ["O Amapá é a porta da Amazônia — vem viver isso.", "Bora, a floresta tá chamando.", "Aqui ninguém tem pressa e o abraço é de casa."],
        "regiao": "Norte",
    },
    "AM": {
        "gírias": ["oxente", "muita coisa boa", "é nóis", "da hora", "bater um papo", "arretado"],
        "costumes": ["Boi Garantido e Caprichoso em Parintins", "tucupi com jambu e maniçoba", "açaí de todos os jeitos", "encontro das águas do Negro com o Solimões", "mercado municipal de manhãzinha", "cultura ribeirinha e dos povos da floresta"],
        "tratamento": "meu consagrado",
        "marcas_orais": ["se liga, é muito bom", "é de doido", "tu não conhece é nada", "pra falar a real", "é nóis mesmo"],
        "fechos": ["Manaus e o Amazonas são maiores que o mapa — vem ver.", "Bora pro boi-bumbá, que o capricho é da gente!", "Aqui o calor é forte, mas o abraço é mais ainda."],
        "regiao": "Norte",
    },
    "BA": {
        "gírias": ["oxente", "arretado", "bom demais", "doidera", "vixe", "bater um papinho", "massa"],
        "costumes": ["acarajé feito na hora pela baiana", "roda de capoeira no Pelourinho", "axé e forró nas ruas", "café com bolo no meio da tarde", "festas de largo e procissões", "cultura afro-baiana viva no dia a dia"],
        "tratamento": "meu bem",
        "marcas_orais": ["vixe, é uma coisa linda", "oxente, como é bom", "arretado demais", "meu bem, vem cá", "é de lamber os dedos"],
        "fechos": ["Vem pra Bahia, que o dendê tá na mesa.", "Bora? A Bahia é grande e a gente não tem pressa.", "O que a Bahia tem, tu não acha em outro lugar — vem viver."],
        "regiao": "Nordeste",
    },
    "CE": {
        "gírias": ["oxente", "massa", "arretado", "da hora", "dar um role", "tá de parabéns"],
        "costumes": ["forró pé-de-serra nas noites de festa", "caranguejada e carne de sol", "praias de Jericoacoara e Canoa Quebrada", "festas juninas das maiores do país", "renda de bilro no litoral", "cajuada gelada no calor"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, é uma beleza", "arretado, viu", "é bom demais o troço", "meu rei, isso aqui é demais", "se liga nessa dica"],
        "fechos": ["Vem pro Ceará, que o sol brilha todo dia — e a simpatia também.", "Bora, meu rei? O Ceará tá te esperando.", "Ceará é terra de gente boa e praia bonita — vem conferir."],
        "regiao": "Nordeste",
    },
    "DF": {
        "gírias": ["massa", "de boa", "se liga", "rolê", "da hora", "tá de parabéns"],
        "costumes": ["feiras de artesanato na Rodoviária do Plano", "churrasco de fim de semana", "pedalada no Lago Paranoá", "gastronomia de todos os cantos do Brasil", "trilhas na Chapada dos Veadeiros", "cultura universitária e de servidores"],
        "tratamento": "parceiro",
        "marcas_orais": ["se liga nessa", "é de boa, meu parceiro", "tá de parabéns o lugar", "é massa demais", "tu não vai se arrepender"],
        "fechos": ["Brasília não é só política — vem andar pelo Eixo e descobrir.", "Vem, que o cerrado é de doer de bonito.", "DF é jovem, diverso e cheio de rolê — aparece."],
        "regiao": "Centro-Oeste",
    },
    "ES": {
        "gírias": ["muito bom", "da hora", "é nóis", "tá de parabéns", "bater um papo", "da massa"],
        "costumes": ["moqueca capixaba na panela de barro", "torto capixaba nas festas", "pão com sardinha na merenda", "praias de Vitória e Guarapari", "romaria de Nossa Senhora da Penha", "capixabada de domingo com a família"],
        "tratamento": "mô",
        "marcas_orais": ["é bom demais, viu", "se tu for lá", "tá de parabéns o lugar", "é da massa, véi", "pra falar a real"],
        "fechos": ["Vem pro Espírito Santo, que a moqueca tá na panela.", "Capixaba é hospitaleiro — vem conhecer o nosso canto.", "Entre montanhas e mar, o ES te espera de braços abertos."],
        "regiao": "Sudeste",
    },
    "GO": {
        "gírias": ["uai", "uaim", "arretado", "muito bom", "da hora", "dar um role"],
        "costumes": ["pequi na comida de todo dia", "arroz com pequi de domingo", "Chapada dos Veadeiros no fim de semana", "sertanejo nas noites de festa", "empadão goiano e feijão tropeiro", "carnaval de rua em Goiânia"],
        "tratamento": "uai",
        "marcas_orais": ["uai, é muito bom", "uaim, tu não conhece", "é arretado demais", "se liga nessa", "vai por mim"],
        "fechos": ["Goiás é coração do Brasil — vem sentir no peito.", "Uai, ainda não veio? Então vem!", "O cerrado goiano é de se apaixonar — aparece por aqui."],
        "regiao": "Centro-Oeste",
    },
    "MA": {
        "gírias": ["oxente", "arretado", "muito da hora", "bom demais", "dar um role", "se liga"],
        "costumes": ["Bumba Meu Boi nas ruas", "reggae no centro de São Luís, a Jamaica brasileira", "cuzcuz de arroz e arroz de cuxá", "azulejos portugueses do centro histórico", "Lençóis Maranhenses na alta temporada", "tambor de crioula nas festas de santo"],
        "tratamento": "meu consagrado",
        "marcas_orais": ["oxente, é demais", "meu consagrado, vem ver", "é de doido de tão bonito", "arretado, viu", "tu vai ficar babando"],
        "fechos": ["O Maranhão é o ritmo do Brasil — vem dançar.", "São Luís é Jamaica tropical, meu consagrado — vem!", "Lençóis, boi e reggae: o Maranhão é de outro mundo."],
        "regiao": "Nordeste",
    },
    "MG": {
        "gírias": ["uai", "sô", "trem", "é nóis", "bão", "di menor", "vixe", "uê"],
        "costumes": ["café coado na hora e pão de queijo quentinho", "comida de fogão a lenha", "cidades históricas de Ouro Preto e Tiradentes", "queijos da serra e doce de leite", "festa do Divino e procissões", "conversa boa na varanda de fim de tarde"],
        "tratamento": "sô",
        "marcas_orais": ["uai, sô", "é um trem bão demais", "vixe, tu não imagina", "é bom demais da conta", "se tu for por lá"],
        "fechos": ["Minas é hospitalidade — vem comer, vem ficar, vem viver.", "Sô, ainda não veio pra Minas? Então vem, uai!", "Em Minas, até o tempo passa mais devagar — vem aproveitar."],
        "regiao": "Sudeste",
    },
    "MS": {
        "gírias": ["bão", "da hora", "muita coisa boa", "se liga", "dar um role", "é nóis"],
        "costumes": ["churrasco pantaneiro", "tereré na cuia com limão e caroba", "vida ribeirinha no Pantanal", "pescaria de pintado e pacu", "por do sol no rio Paraguai", "cultura gaúcha de fronteira e guarani"],
        "tratamento": "parceiro",
        "marcas_orais": ["é um barato danado", "se liga, é demais", "tu vai ficar de queixo caído", "é bão demais", "vai por mim, parceiro"],
        "fechos": ["O Pantanal é o maior aquário do mundo — vem mergulhar nisso.", "Mato Grosso do Sul é terra de sol, rio e gente boa — aparece.", "Bora? O tereré já tá na cuia, o Pantanal tá te esperando."],
        "regiao": "Centro-Oeste",
    },
    "MT": {
        "gírias": ["bão", "da hora", "se liga", "muita coisa boa", "dar um role", "é nóis"],
        "costumes": ["churrasco e arroz carreteiro", "Chapada dos Guimarães", "pescaria no rio Cuiabá", "caldo de piranha e pacu assado", "festas de peão no interior", "cultura mato-grossense de fronteira"],
        "tratamento": "parceiro",
        "marcas_orais": ["é um barato, sô", "se liga nessa", "tu não conhece é nada", "é bão demais da conta", "vai por mim"],
        "fechos": ["Mato Grosso é gigante em tudo — inclusive no coração.", "A Chapada tá de portas abertas, vem!", "Cuiabá é calor humano de verdade — aparece por aqui."],
        "regiao": "Centro-Oeste",
    },
    "PA": {
        "gírias": ["oxente", "da hora", "é nóis", "muito da hora", "dar um role", "bater um papo"],
        "costumes": ["açaí na tigela todo santo dia", "Ver-o-Peso de madrugada", "tucupi, maniçoba e pato no tucupi", "Círio de Nazaré em outubro", "carimbó nas festas", "ilhas e praias de Salinas no fim de semana"],
        "tratamento": "meu consagrado",
        "marcas_orais": ["oxente, é muito bom", "meu consagrado, vem cá", "é de doido", "se tu for por lá", "é bom demais, viu"],
        "fechos": ["Belém é sabor, fé e floresta — vem viver isso.", "O Pará é grande e generoso — vem conhecer o nosso canto.", "Açaí, tucupi e carimbó: o Pará é de outro nível. Vem!"],
        "regiao": "Norte",
    },
    "PB": {
        "gírias": ["oxente", "arretado", "muito bom", "da hora", "dar um role", "se liga"],
        "costumes": ["praia do Cabo Branco e o pôr do sol mais oriental", "cachaça de alambique e rapadura", "coco de roda e forró", "feira de Campina Grande", "Maior São João do Mundo", "cordel e literatura de feira"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, é uma beleza", "arretado, viu", "é bom demais o lugar", "meu rei, vem ver", "tu vai se apaixonar"],
        "fechos": ["A Paraíba é o sol que nasce primeiro — vem viver o amanhecer.", "João Pessoa é calma e beleza — vem respirar fundo.", "Bora? A Paraíba tá de braços abertos."],
        "regiao": "Nordeste",
    },
    "PE": {
        "gírias": ["oxente", "arretado", "doido", "muito bom", "da hora", "se liga"],
        "costumes": ["frevo no Carnaval do Recife", "maracatu e caboclinhos", "bolo de rolo fininho e cartola de sobremesa", "carne de sol com mandioca", "Olinda de ladeiras e bonecos gigantes", "galinha à cabidela de domingo"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, meu rei", "é arretado demais", "doido, é muito bom", "se liga nessa", "tu não imagina a beleza"],
        "fechos": ["Pernambuco é cultura viva — vem dançar frevo com a gente.", "Bora, que o frevo não espera!", "Recife e Olinda são um só coração — vem sentir."],
        "regiao": "Nordeste",
    },
    "PI": {
        "gírias": ["oxente", "arretado", "muito bom", "da hora", "dar um role", "se liga"],
        "costumes": ["carnaval de Parnaíba", "cajuína gelada e carne de sol", "Delta do Parnaíba de barco", "Serra da Capivara e sua história antiga", "vaquejada e forró pé-de-serra", "festas de padroeiro no interior"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, é demais", "meu rei, vem ver", "é arretado o lugar", "tu vai gostar demais", "se liga nessa dica"],
        "fechos": ["O Piauí é surpresa boa — vem descobrir.", "Delta, serra e forró: o Piauí é completo. Vem!", "Bora? O Piauí te espera com cajuína na mesa."],
        "regiao": "Nordeste",
    },
    "PR": {
        "gírias": ["bah", "tri bom", "da hora", "bacana", "se liga", "é nóis"],
        "costumes": ["churrasco e polenta de tradição italiana e alemã", "Cataratas do Iguaçu no roteiro", "erva-mate e chimarrão no inverno", "feiras coloniais do interior", "festa do pinhão na serra", "futebol e feijão tropeiro de domingo"],
        "tratamento": "bah",
        "marcas_orais": ["bah, é tri bom", "tu não conhece é nada", "é um barato danado", "se liga nessa", "vai por mim"],
        "fechos": ["O Paraná é frio na serra e calor humano em todo lugar — vem.", "Bah, ainda não veio? Então aparece!", "Da capital ao interior, o Paraná é gente boa de verdade."],
        "regiao": "Sul",
    },
    "RJ": {
        "gírias": ["massa", "da hora", "se liga", "rolê", "é nóis", "de boa", "tá de parabéns"],
        "costumes": ["pôr do sol na Praia do Arpoador", "pedal pela orla de Ipanema", "feijoada de sábado", "samba e pagode nos fins de semana", "trilhas do Pão de Açúcar e da Pedra da Gávea", "praias de Cabo Frio e Búzios no verão"],
        "tratamento": "meu",
        "marcas_orais": ["se liga, é massa", "meu, tu não vai acreditar", "é da hora demais", "de boa, vem cá", "tá de parabéns o lugar"],
        "fechos": ["O Rio é ritmo, sol e gente — vem viver o apê.", "Bora? A cidade maravilhosa tá te esperando.", "Rio de Janeiro não se explica, se sente — vem sentir."],
        "regiao": "Sudeste",
    },
    "RN": {
        "gírias": ["oxente", "arretado", "muito bom", "da hora", "dar um role", "se liga"],
        "costumes": ["praias de Genipabu e Pipa", "dunas de ponta a ponta", "carne de sol no pirão de leite de cabra", "forró pé-de-serra e quadrilhas", "salinas de Mossoró", "festa de Nossa Senhora da Conceição"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, é uma beleza", "arretado, viu", "é bom demais o lugar", "meu rei, vem ver", "tu vai se apaixonar"],
        "fechos": ["O Rio Grande do Norte é sol o ano inteiro — vem tomar banho de mar.", "Bora? Pipa e as dunas tão te esperando.", "RN é pequeno no mapa e gigante na praia — aparece."],
        "regiao": "Nordeste",
    },
    "RO": {
        "gírias": ["oxente", "da hora", "é nóis", "muito da hora", "dar um role", "bater um papo"],
        "costumes": ["peixada e tambaqui assado", "cultura ribeirinha do Madeira", "festivais de inverno de Porto Velho", "café de Rondônia, dos mais premiados do país", "tradição da colonização de toda parte do Brasil", "igreja de madeira e festas de arraial"],
        "tratamento": "amigo",
        "marcas_orais": ["oxente, é muito bom", "é de doido", "se tu for por lá", "é bom demais, viu", "pra falar a real"],
        "fechos": ["Rondônia é a terra do café bom e do povo acolhedor — vem provar.", "Bora? O Madeira tá esperando a tua canoa.", "Aqui se mistura o Brasil inteiro — vem conhecer essa mistura."],
        "regiao": "Norte",
    },
    "RR": {
        "gírias": ["oxente", "da hora", "é nóis", "muito da hora", "dar um role", "se liga"],
        "costumes": ["cultura indígena Yanomami e Macuxi", "lavrado e cerrado roraimense", "Monte Roraima nos roteiros de aventura", "peixe assado à beira do rio", "festas de fronteira com a Venezuela", "gastronomia de peixe de água doce"],
        "tratamento": "amigo",
        "marcas_orais": ["é um barato danado", "se liga, é demais", "tu não conhece é nada", "é bom demais", "vai por mim"],
        "fechos": ["Roraima é o cantinho indígena do Brasil — vem viver essa cultura.", "O lavrado é imenso e bonito — aparece por aqui.", "Vem, que o Monte Roraima tá de portas abertas."],
        "regiao": "Norte",
    },
    "RS": {
        "gírias": ["bah", "tri bom", "da hora", "bacana", "guri", "tchê"],
        "costumes": ["churrasco na churrasqueira de chão", "chimarrão em roda de mate", "festa do peão e rodeio crioulo", "pampa gaúcho e tradição campeira", "arroz de carreteiro e galeto", "futebol de fim de tarde"],
        "tratamento": "bah",
        "marcas_orais": ["bah, guri, é tri bom", "tchê, tu não conhece", "é um barato danado", "se liga nessa", "vai por mim, tchê"],
        "fechos": ["O Rio Grande do Sul é tradição e churrasco — vem sentar na roda do mate.", "Bah, ainda não veio? Então aparece, tchê!", "Gaúcho é hospitaleiro quando quer — e quer sempre. Vem!"],
        "regiao": "Sul",
    },
    "SC": {
        "gírias": ["bah", "tri bom", "da hora", "bacana", "se liga", "é nóis"],
        "costumes": ["ostra e marisco na costa", "festas de Oktoberfest em Blumenau", "tradição açoriana na ilha de Florianópolis", "praias de Balneário Camboriú e Praia do Rosa", "caminhões de fondue no inverno da serra", "cultura de imigração alemã e italiana"],
        "tratamento": "bah",
        "marcas_orais": ["bah, é tri bom", "tu não conhece é nada", "é um barato danado", "se liga nessa", "vai por mim"],
        "fechos": ["Santa Catarina é praia no verão e neve na serra — vem ver as duas.", "Bah, aparece! A ilha tá te esperando.", "SC é o cantinho europeu do Brasil — vem conhecer."],
        "regiao": "Sul",
    },
    "SE": {
        "gírias": ["oxente", "arretado", "muito bom", "da hora", "dar um role", "se liga"],
        "costumes": ["carnaval de Aracaju e de Laranjeiras", "queijo coalho e rapadura", "praças à beira-mar na orla de Aracaju", "festas juninas no interior", "cultura do São Francisco na divisa", "coco de roda e forró"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, é uma beleza", "arretado, viu", "é bom demais o lugar", "meu rei, vem ver", "tu vai se apaixonar"],
        "fechos": ["Sergipe é o menor estado e um dos maiores em simpatia — vem.", "Bora? A orla de Aracaju tá de portas abertas.", "SE é tranquilidade à beira-mar — aparece por aqui."],
        "regiao": "Nordeste",
    },
    "SP": {
        "gírias": ["massa", "da hora", "se liga", "rolê", "é nóis", "de boa", "mermão"],
        "costumes": ["pizza de sábado à noite", "café Paulista e pastel de feira", "trânsito e vida corrida da capital", "sítios e cachoeiras do interior", "futebol de várzea no fim de semana", "festas de peão do interior"],
        "tratamento": "mermão",
        "marcas_orais": ["se liga, é massa", "mermão, tu não vai acreditar", "é da hora demais", "de boa, vem cá", "tá de parabéns o lugar"],
        "fechos": ["São Paulo é o Brasil inteiro numa state só — vem viver.", "Bora? A terra da garoa e do rolê tá te esperando.", "SP não para — e quando para, é pra te receber. Vem!"],
        "regiao": "Sudeste",
    },
    "TO": {
        "gírias": ["oxente", "arretado", "muito bom", "da hora", "dar um role", "se liga"],
        "costumes": ["Festa do Círio de Palmas", "Jalapão e suas fervedouros", "praias de rio no Araguaia", "pequi e arroz com pequi na comida", "cultura do bumba meu boi tocantinense", "cavalgadas e festas de peão no interior"],
        "tratamento": "meu rei",
        "marcas_orais": ["oxente, é uma beleza", "arretado, viu", "é bom demais o lugar", "meu rei, vem ver", "se liga nessa dica"],
        "fechos": ["O Tocantins é o coração novo do Brasil — vem descobrir.", "Bora? O Jalapão tá de fervedouro aberto.", "TO é rio, praia de água doce e gente boa — aparece."],
        "regiao": "Norte",
    },
}


def load_perfil(uf: str):
    """Devolve o perfil da UF, normalizada."""
    return PERFIS[uf.upper()]
